# Generated by Django 6.0.3 on 2026-04-08

import uuid

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0004_location_portfolio_and_profile_locations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=portfolio.models.portfolio_image_upload_path
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal"),
                            ("COUPLE", "Couple"),
                            ("EVENT", "Event"),
                            ("WEDDING", "Wedding"),
                            ("FAMILY", "Family"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="portfolios",
                        to="user.photographerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["photographer", "-created_at"],
                name="portfolio_p_photogr_9f85af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["category", "-created_at"],
                name="portfolio_p_categor_00a8af_idx",
            ),
        ),
    ]
