# Generated by Django 6.0.3 on 2026-05-06 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portfolio',
            new_name='portfolio_p_photogr_0c07e9_idx',
            old_name='portfolio_p_photogr_9f85af_idx',
        ),
        migrations.RenameIndex(
            model_name='portfolio',
            new_name='portfolio_p_categor_24f79e_idx',
            old_name='portfolio_p_categor_00a8af_idx',
        ),
    ]
