# Generated by Django 6.0.3 on 2026-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avatar_public_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_public_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default=''),
        ),
    ]
