# Generated by Django 6.0.3 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("user", "0003_remove_user_avatar_public_url_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="photographerprofile",
            name="active_locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="locations",
                to="locations.location",
            ),
        ),
    ]
