# Generated by Django 6.0.4 on 2026-04-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_location_portfolio_and_profile_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerprofile',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
