# Generated by Django 6.0.4 on 2026-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_photographerprofile_rating_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.URLField(blank=True, default=''),
        ),
    ]