# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_user_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photographerprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="working_models",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="photographerprofile",
            name="working_packages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="PhotographerFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photographer_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="user.photographerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "-created_at"],
                        name="user_photog_custome_30dbfe_idx",
                    ),
                    models.Index(
                        fields=["photographer", "-created_at"],
                        name="user_photog_photogr_ab43ad_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "photographer"),
                        name="unique_customer_photographer_favorite",
                    ),
                ],
            },
        ),
    ]
