# Generated by Django 6.0.3 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_province", models.CharField(max_length=120)),
                ("district", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["city_province", "district"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("city_province", "district"),
                        name="unique_city_province_district",
                    )
                ],
            },
        ),
    ]
