# Generated by Django 6.0.5 on 2026-05-06 07:34

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': [django.db.models.functions.text.Lower('city_province'), django.db.models.functions.text.Lower('district')]},
        ),
    ]
