# Generated by Django 6.0.3 on 2026-04-08 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PERSONAL', 'Personal'), ('COUPLE', 'Couple'), ('EVENT', 'Event'), ('WEDDING', 'Wedding'), ('FAMILY', 'Family')], max_length=20)),
                ('shoot_date', models.DateField()),
                ('deadline_date', models.DateTimeField()),
                ('environment', models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('STUDIO', 'Studio')], max_length=20)),
                ('requires_makeup', models.BooleanField(default=False)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='locations.location')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bookings.booking')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'category'], name='bookings_bo_status_27ba20_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', '-created_at'], name='bookings_bo_custome_10bd54_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['shoot_date'], name='bookings_bo_shoot_d_02096e_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('budget_max__gte', models.F('budget_min'))), name='booking_budget_max_gte_budget_min'),
        ),
        migrations.AddIndex(
            model_name='bookingbid',
            index=models.Index(fields=['booking', 'status'], name='bookings_bo_booking_03ed71_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingbid',
            index=models.Index(fields=['photographer', '-created_at'], name='bookings_bo_photogr_616f6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingbid',
            constraint=models.UniqueConstraint(fields=('booking', 'photographer'), name='unique_booking_bid_per_photographer'),
        ),
    ]
